# Generated by Django 5.2 on 2025-04-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phonenumber', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('age', models.IntegerField(max_length=5)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
